branch-defaults:
  default:
    environment: imperium-web-prod
    group_suffix: null
deploy:
  artifact: deploy.zip
global:
  application_name: imperium-web
  branch: null
  default_ec2_keyname: imperium
  default_platform: Node.js 12
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: imperium
  repository: null
  sc: null
  workspace_type: Application
